In [143]:
import pandas as pd
import csv
import numpy as np
from sklearn import preprocessing
import matplotlib.pyplot as plt 
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
import seaborn as sns
from statistics import mean
import sklearn as sk
from numpy import array

In [129]:
#creating my dataframe
mydata=pd.DataFrame({"Db": [], "Hz": []})

In [130]:
#filling the dataframe with the file from SJapp
#i have all files in the same directory as .py file, they are named progressively with the sintax:
#   PROJECTNAME Registrazione n.csv    with n in [1,2...]

#my project name is sl, so i run a for cycle within the number of record i have and fill my dataframe
for i in range(1,27):
    cmd='pd.read_csv("sl Registrazione '+str(i)+'.csv")' 
    df=eval(cmd)
    
    Db=df["DecibelSource"].dropna()  #clean from NAs
    Hz=df["PitchSensor"].dropna()
    
    
    
    Db=list(Db)
    Hz=list(Hz)
    
    #Db=Db.reset_index(drop=True)
    #Hz=Hz.reset_index(drop=True)
    
    
    
    mydata=mydata.append({'Db' : Db , 'Hz' : Hz} ," ignore_index=True")  #write new line with the value found in the CSV

In [131]:
mydata

,Db,Hz
0,"[40.11908896305083, 38.55048968529117, 41.3890...","[33.58795166015625, 47.0947265625, 47.09472656..."
1,"[43.245460678519926, 46.62764517379549, 44.068...","[110.634765625, 56.9189453125, 56.9189453125, ..."
2,"[31.46325334489448, 30.138391223801467, 37.854...","[200.35498046875, 200.35498046875, 147.8122384..."
3,"[11.721636092573625, 11.755092248181482, 28.87...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 138.950195..."
4,"[32.97497812626419, 35.09493922030071, 39.9002...","[118.28938802083334, 118.28938802083334, 64.01..."
5,"[28.939335100428373, 23.38108390264873, 23.423...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 135.200195..."
6,"[24.914226684015894, 18.161746943812663, 25.36...","[544.8779296875, 544.8779296875, 0.0, 0.0, 43...."
7,"[16.632054249889514, 16.199825964892927, 13.14...","[57.36328125, 57.36328125, 0.0, 0.0, 0.0, 0.0,..."
8,"[26.703105789748143, 23.028643548912072, 24.85...","[405.380859375, 0.0, 0.0, 0.0, 0.0, 0.0, 1757...."
9,"[15.314789170422552, 11.760912590556812, 50.36...","[0.0, 0.0, 240.57942708333331, 240.57942708333..."
10,"[30.891983668051488, 25.538830266438747, 47.66...","[211.95033482142856, 211.95033482142856, 493.4..."
11,"[41.64917666100958, 41.605585621075576, 44.299...","[117.12109375, 170.359375, 170.359375, 143.804..."
12,"[49.783905349830704, 49.783905349830704, 50.55...","[79.599609375, 79.599609375, 45.380859375, 33...."
13,"[43.355581880658605, 51.10569510086129, 48.547...","[440.3515625, 517.83984375, 517.83984375, 371...."
14,"[56.26891356092757, 56.28882212708075, 58.4358...","[100.4345703125, 47.4462890625, 49.9169921875,..."
15,"[19.45318383545405, 18.038502361992837, 16.372...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 339.233398..."
16,"[55.10859961906438, 51.864688959738814, 51.652...","[291.0975477430556, 331.6312255859375, 331.631..."
17,"[42.12162077532345, 43.92194437260599, 42.2660...","[152.61346449387042, 152.61346449387042, 152.6..."
18,"[18.53375343933852, 19.35402147400604, 24.6527...","[209.19202309830175, 0.0, 0.0, 0.0, 0.0, 328.3..."
19,"[15.439695537087596, 19.230612408148648, 19.30...","[0.0, 0.0, 0.0, 3640.048828125, 3640.048828125..."
20,"[19.45318383545405, 18.038502361992837, 16.372...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 339.233398..."
21,"[51.509708077318315, 49.206463639207875, 53.09...","[83.5404052734375, 83.5404052734375, 83.540405..."
22,"[15.31811881710768, 15.57176992846104, 15.7901...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
23,"[31.236931563575826, 26.150167135167607, 36.68...","[0.0, 125.9320068359375, 125.9320068359375, 12..."
24,"[29.52738094783193, 27.660100580824576, 25.288...","[268.5400390625, 230.9423828125, 230.942382812..."
25,"[33.119446531464924, 28.733594908973828, 33.64...","[419.1162109375, 419.1162109375, 419.116210937..."

In [132]:
#now i read the csv with the labels associated to my dataframe
labels=pd.read_csv("labels.csv", sep=";")

In [7]:
#labels

    Male Feeling    Person
0      1   happy  giuliano
1      1   angry  giuliano
2      1   angry     other
3      1     sad  giuliano
4      1   happy  giuliano
5      0   happy     other
6      1     sad     other
7      0  steady     other
8      1  steady     mario
9      0  steady     other
10     0  steady  cristina
11     0  steady     other
12     0  steady  cristina
13     1   angry     other
14     1  steady     other
15     0   angry     other
16     0   happy     other
17     0   happy     other
18     0   happy     other
19     0  steady     other
20     0     sad     other
21     1   angry     other
22     1   happy     other
23     1   happy     other
24     1  steady     other
25     1     sad     other

In [133]:
#let's concatenate the two tables
result = pd.concat([mydata, labels], axis=1, sort=False)

In [134]:
result

,Db,Hz,Male,Feeling,Person
0,"[40.11908896305083, 38.55048968529117, 41.3890...","[33.58795166015625, 47.0947265625, 47.09472656...",1,happy,giuliano
1,"[43.245460678519926, 46.62764517379549, 44.068...","[110.634765625, 56.9189453125, 56.9189453125, ...",1,angry,giuliano
2,"[31.46325334489448, 30.138391223801467, 37.854...","[200.35498046875, 200.35498046875, 147.8122384...",1,angry,other
3,"[11.721636092573625, 11.755092248181482, 28.87...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 138.950195...",1,sad,giuliano
4,"[32.97497812626419, 35.09493922030071, 39.9002...","[118.28938802083334, 118.28938802083334, 64.01...",1,happy,giuliano
5,"[28.939335100428373, 23.38108390264873, 23.423...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 135.200195...",0,happy,other
6,"[24.914226684015894, 18.161746943812663, 25.36...","[544.8779296875, 544.8779296875, 0.0, 0.0, 43....",1,sad,other
7,"[16.632054249889514, 16.199825964892927, 13.14...","[57.36328125, 57.36328125, 0.0, 0.0, 0.0, 0.0,...",0,steady,other
8,"[26.703105789748143, 23.028643548912072, 24.85...","[405.380859375, 0.0, 0.0, 0.0, 0.0, 0.0, 1757....",1,steady,mario
9,"[15.314789170422552, 11.760912590556812, 50.36...","[0.0, 0.0, 240.57942708333331, 240.57942708333...",0,steady,other
10,"[30.891983668051488, 25.538830266438747, 47.66...","[211.95033482142856, 211.95033482142856, 493.4...",0,steady,cristina
11,"[41.64917666100958, 41.605585621075576, 44.299...","[117.12109375, 170.359375, 170.359375, 143.804...",0,steady,other
12,"[49.783905349830704, 49.783905349830704, 50.55...","[79.599609375, 79.599609375, 45.380859375, 33....",0,steady,cristina
13,"[43.355581880658605, 51.10569510086129, 48.547...","[440.3515625, 517.83984375, 517.83984375, 371....",1,angry,other
14,"[56.26891356092757, 56.28882212708075, 58.4358...","[100.4345703125, 47.4462890625, 49.9169921875,...",1,steady,other
15,"[19.45318383545405, 18.038502361992837, 16.372...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 339.233398...",0,angry,other
16,"[55.10859961906438, 51.864688959738814, 51.652...","[291.0975477430556, 331.6312255859375, 331.631...",0,happy,other
17,"[42.12162077532345, 43.92194437260599, 42.2660...","[152.61346449387042, 152.61346449387042, 152.6...",0,happy,other
18,"[18.53375343933852, 19.35402147400604, 24.6527...","[209.19202309830175, 0.0, 0.0, 0.0, 0.0, 328.3...",0,happy,other
19,"[15.439695537087596, 19.230612408148648, 19.30...","[0.0, 0.0, 0.0, 3640.048828125, 3640.048828125...",0,steady,other
20,"[19.45318383545405, 18.038502361992837, 16.372...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 339.233398...",0,sad,other
21,"[51.509708077318315, 49.206463639207875, 53.09...","[83.5404052734375, 83.5404052734375, 83.540405...",1,angry,other
22,"[15.31811881710768, 15.57176992846104, 15.7901...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",1,happy,other
23,"[31.236931563575826, 26.150167135167607, 36.68...","[0.0, 125.9320068359375, 125.9320068359375, 12...",1,happy,other
24,"[29.52738094783193, 27.660100580824576, 25.288...","[268.5400390625, 230.9423828125, 230.942382812...",1,steady,other
25,"[33.119446531464924, 28.733594908973828, 33.64...","[419.1162109375, 419.1162109375, 419.116210937...",1,sad,other

In [10]:
#result.to_csv(r'myfile.csv',index=False)

# Regression

In [138]:
#evaluate mininum len
mini=100000000000000000
for i in range(len(result)):
    now=len(result["Db"][i])
    #print(str(i)+ " " +str(now))
    if now<mini:
        mini=now
mini

0 160
1 160
2 160
3 160
4 160
5 160
6 160
7 160
8 160
9 160
10 160
11 160
12 160
13 160
14 160
15 160
16 160
17 160
18 160
19 160
20 160
21 160
22 160
23 160
24 160
25 160

160

In [137]:
#same len for all

for i in range(len(result)):
    result["Db"][i]=result["Db"][i][0:mini]

for i in range(len(result)):
    result["Hz"][i]=result["Hz"][i][0:mini]

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  import sys

In [139]:
#selecting only male and female to study their properties
male=result.loc[result["Male"]==1]
male=male.reset_index(drop=True)  #setting new indexes for the new DF
female=result.loc[result["Male"]==0]
female=female.reset_index(drop=True)

In [144]:
##let's see how the means differs
somma=0
for i in range(len(male)):
    somma+=mean(male["Db"][i])
print("mean for DB in male is "+str(round(somma/(len(male)+1),2)))

somma=0
for i in range(len(male)):
    somma+=mean(male["Hz"][i])
print("mean for HZ in male is " + str(round(somma/(len(male)+1),2)))

##now for female..
somma=0
for i in range(len(female)):
    somma+=mean(female["Db"][i])
print("mean for DB in female is "+str(round(somma/(len(female)+1),2)))

somma=0
for i in range(len(female)):
    somma+=mean(female["Hz"][i])
print("mean for HZ in female is " +str(round(somma/(len(female)+1),2)))

mean for DB in male is 40.12
mean for HZ in male is 216.56
mean for DB in female is 36.95
mean for HZ in female is 263.81

In [142]:

mean(male["Db"][1])

48.174869844598284

In [81]:
"""
import statsmodels.api as sm

y=result["Male"]
X=result[["Db","Hz"]]
logit_model=sm.Logit(y,X.astype(float))
model=logit_model.fit()
print(result.summary2())

ValueError: setting an array element with a sequence.

In [126]:
y=result["Male"]
X=result[["Db"]]
y=array(y)
y=y.reshape(-1, 1)

#X=array(X)
X

                                                   Db
0   [40.11908896305083, 38.55048968529117, 41.3890...
1   [43.245460678519926, 46.62764517379549, 44.068...
2   [31.46325334489448, 30.138391223801467, 37.854...
3   [11.721636092573625, 11.755092248181482, 28.87...
4   [32.97497812626419, 35.09493922030071, 39.9002...
5   [28.939335100428373, 23.38108390264873, 23.423...
6   [24.914226684015894, 18.161746943812663, 25.36...
7   [16.632054249889514, 16.199825964892927, 13.14...
8   [26.703105789748143, 23.028643548912072, 24.85...
9   [15.314789170422552, 11.760912590556812, 50.36...
10  [30.891983668051488, 25.538830266438747, 47.66...
11  [41.64917666100958, 41.605585621075576, 44.299...
12  [49.783905349830704, 49.783905349830704, 50.55...
13  [43.355581880658605, 51.10569510086129, 48.547...
14  [56.26891356092757, 56.28882212708075, 58.4358...
15  [19.45318383545405, 18.038502361992837, 16.372...
16  [55.10859961906438, 51.864688959738814, 51.652...
17  [42.12162077532345, 43.92194437260599, 42.2660...
18  [18.53375343933852, 19.35402147400604, 24.6527...
19  [15.439695537087596, 19.230612408148648, 19.30...
20  [19.45318383545405, 18.038502361992837, 16.372...
21  [51.509708077318315, 49.206463639207875, 53.09...
22  [15.31811881710768, 15.57176992846104, 15.7901...
23  [31.236931563575826, 26.150167135167607, 36.68...
24  [29.52738094783193, 27.660100580824576, 25.288...
25  [33.119446531464924, 28.733594908973828, 33.64...

In [127]:

model = sk.linear_model.LinearRegression()
model.fit(y, X)
"LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False) a[5], b[5], model.predict([a[5]])"

ValueError: setting an array element with a sequence.